[package]
name = "regexes"
version = "1.0.0"
authors = ["dystroy <denys.seguret@gmail.com>"]
edition = "2018"
description = "An example for lazy-regex"
license = "MIT"
readme = "README.md"

[dependencies]
lazy-regex = { path = "../.." }
regex = "1.4"
